### ISSUE TITLE
polyswarm/ipfs:latest not available

### ISSUE THREAD

**Issue by pepijnblom** [polyswarm/polyswarm#1]
Hi I'm trying to use your docker-compose file but it seems it's requiring an image which is not public or does not exist (polyswarm/ipfs:latest).

Would love to have a look :)

**Comment by mjkoo** [comment]
Hi, sorry for the delayed reply, we've been busy developing out other parts of our network (to be released as open source soon!) The image in question is just built from the Dockerfile in go-ipfs, the compose file has been updated to reference the one at https://hub.docker.com/r/ipfs/go-ipfs/

**Comment by mjkoo** [comment]
Resolved in 81768c16d699e4f88fd92c22c706ee63d2c796c7
